server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_gestiondestock
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
## specify DBMS
  jpa:
    database: mysql
    show-sql: true
## hibernate DDL Auto (create , create-drop, update)
    hibernate:
      ddl-auto: update